# Install required packages

install.packages("here") # to manage file paths
install.packages("lintr")
install.packages("styler")

# Load required libraries
library(here)
library(lintr)

# Before we get started Read The Documentation (RTD!) for the lintr package:
# https://lintr.r-lib.org/articles/lintr.html 
# This will tell you useful info about the functions and how to use them.

# Exercises:
# ---- Running lintr ------------------
# 1. Using the `lint` function lint either your own script or one of the provided scripts.

# Example code to lint one of my scripts: 
lint(here("exercise/supplementary_tables_excel.R"))
# Hint: alternative to running the above you can click on "Addins" 
# and under the "LINTR" heading click on "lint current file".

# 2. Go through the linting results and fix a couple of the issues that are raised 
# (if you're stuck see my video here: https://youtu.be/I736wZs_QiE).

# ---- Configuring linters -------------
# 3. By default lintr uses the R tidyverse style. 
# Create a lintr configuration file and add a new linter. 
# (Tip: Read The Documentation: https://lintr.r-lib.org/articles/lintr.html#configuring-linters)
# Tip: if you updated your config but it's still showing a linter you set to NULL try restarting your R session to reload the config.

# A minimal .lintr file can be generated by running use_lintr() in the project directory.
use_lintr() 
# open .lintr and edit it to add a new linter

# See available linters to add
?linters

# I changed my config file to contain:
# linters: linters_with_defaults(
#   absolute_path_linter(),
#   line_length_linter(120))
# encoding: "UTF-8"

# 4. Try turning off the line_length_linter to remove any linting warnings about line length.
# We can do this by editing the config to the following:
# linters: linters_with_defaults(
#   absolute_path_linter(),
#   line_length_linter = NULL
#   encoding: "UTF-8"
# or for this session only and to override the config we can run:
# options(
#   lintr.linters = lintr::linters_with_defaults(
#   line_length_linter = NULL))


# ---- Exclusions ---------------------
# 5. Try and exclude certain lines of code from linting.
# I edited line 2 of "exercise/supplementary_tables_excel.R" to include "nolint":
# "# nolint Clumping / finemapping" to line 
# see: https://lintr.r-lib.org/articles/lintr.html#excluding-lines-of-code 
# also use "nolint start" and "nolint end" to exclude a block of code from linting
# another way is to exclude lines via the config file :https://lintr.r-lib.org/articles/lintr.html#excluding-lines-via-the-config-file

# ---- Automations --------------------
# 6. Use styler to automate some of these linting markers.
# Please read documentation here first: https://www.tidyverse.org/blog/2017/12/styler-1.0.0/
library(styler)
style_file(here("exercise/supplementary_tables_excel.R"))
style_file(here("exercise/supplementary_tables_excel_functions.R"))
# manually check the scripts to see what changed

# 7. Automate linting on every push to GitHub, using GitHub actions (Tip: Read The Documentation: )
usethis::use_github_action("lint-project")
# edited to only run linting on "exercise/supplementary_tables_excel.R"
# because "LINTR_ERROR_ON_LINT: true" then the action will fail if there are any linting errors

